//HintName: Test.Qualified.g.cs
// <auto-generated by UnionSourceGen />
#nullable enable
using System;
using System.Threading.Tasks;
namespace Test
{

    public readonly partial struct Qualified : IEquatable<Qualified>
    {
		private readonly object? _valueRef;
		private readonly int _value0;
		private readonly UnionGen.InternalUtil.StateByte _state;

		private Qualified(int index, int actualTypeIndex)
		{
			_state = new UnionGen.InternalUtil.StateByte(index, actualTypeIndex);
		}

		public Qualified(int value): this(0, 0)
		{
			_value0 = value;
		}

		public Qualified(string value): this(UnionGen.InternalUtil.StateByte.RefTypeIndex, 1)
		{
			_valueRef = value;
		}

		[Obsolete(UnionGen.InternalUtil.UnionGenInternalConst.DefaultConstructorWarning, true)]
		public Qualified(): this(0, 0) {}

		public bool IsInt => _state.ActualTypeIndex == 0;
		public bool IsString => _state.ActualTypeIndex == 1;

		public int AsInt() =>
			IsInt
				? _value0
				: throw UnionGen.InternalUtil.ExceptionHelper.ThrowNotOfType(GetTypeName(0), GetTypeName(_state.ActualTypeIndex));
		
		public string AsString() =>
			IsString
				? (string) _valueRef!
				: throw UnionGen.InternalUtil.ExceptionHelper.ThrowNotOfType(GetTypeName(1), GetTypeName(_state.ActualTypeIndex));

		public static implicit operator Qualified(int value) => new Qualified(value);
		public static implicit operator Qualified(string value) => new Qualified(value);
		public static bool operator ==(Qualified left, Qualified right) => left.Equals(right);
		public static bool operator !=(Qualified left, Qualified right) => !left.Equals(right);

		public TResult Match<TResult>(Func<int, TResult> withInt, Func<string, TResult> withString) => 		
			_state.ActualTypeIndex switch
			{
				0 => withInt(_value0),
				1 => withString((string)_valueRef!),
				_ => throw UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(_state.ActualTypeIndex)
			};

		public async ValueTask<TResult> MatchAsync<TResult>(Func<int, ValueTask<TResult>> withInt, Func<string, ValueTask<TResult>> withString) => 		
			_state.ActualTypeIndex switch
			{
				0 => await withInt(_value0),
				1 => await withString((string)_valueRef!),
				_ => throw UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(_state.ActualTypeIndex)
			};

		public void Switch(Action<int> forInt, Action<string> forString)		
		{
			switch (_state.ActualTypeIndex)
			{
				case 0: forInt(_value0); break;
				case 1: forString((string)_valueRef!); break;
				default: throw UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(_state.ActualTypeIndex);
			}
		}

		public async ValueTask SwitchAsync(Func<int, ValueTask> forInt, Func<string, ValueTask> forString)		
		{
			switch (_state.ActualTypeIndex)
			{
				case 0: await forInt(_value0); break;
				case 1: await forString((string)_valueRef!); break;
				default: throw UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(_state.ActualTypeIndex);
			}
		}

		public override string ToString() => 		
			_state.ActualTypeIndex switch
			{
				0 => _value0.ToString()!,
				1 => _valueRef?.ToString() ?? UnionGen.InternalUtil.UnionGenInternalConst.NullString,
				_ => throw UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(_state.ActualTypeIndex)
			};

		public bool Equals(Qualified other) => 
			_state.ActualTypeIndex == other._state.ActualTypeIndex
				&& _state.ActualTypeIndex switch 
				{
					0 => _value0.Equals(other._value0),
					1 => ReferenceEquals(_valueRef, other._valueRef) || (_valueRef?.Equals(other._valueRef) ?? false),
					_ => false
				};

		public override bool Equals(object? obj)
		{
			if (ReferenceEquals(null, obj))
			{
				return false;
			}
			return obj is Qualified other && Equals(other);
		}

		public override int GetHashCode(){		
			unchecked
			{
				var hash = _state.ActualTypeIndex switch
				{
					0 => _value0.GetHashCode(),
					1 => _valueRef?.GetHashCode() ?? 0,
					_ => 0
				};
				return (hash * 397) ^ _state.ActualTypeIndex;
			}
		}

		public string GetTypeName(int index) =>
			index switch 
			{
				0 => "int",
				1 => "string",
				_ => throw UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(index)
			};

    }

}
