//HintName: Test.StringOrException.g.cs
// <auto-generated by UnionSourceGen />
#nullable enable
namespace Test
{

    public readonly partial struct StringOrException : global::System.IEquatable<StringOrException>
    {
		private readonly object? _valueRef;
		private readonly global::UnionGen.InternalUtil.StateByte _state;

		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		private StringOrException(int index, int actualTypeIndex)
		{
			_state = new global::UnionGen.InternalUtil.StateByte(index, actualTypeIndex);
		}

		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public StringOrException(string value): this(global::UnionGen.InternalUtil.StateByte.RefTypeIndex, 0)
		{
			_valueRef = value;
		}

		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public StringOrException(global::System.Exception value): this(global::UnionGen.InternalUtil.StateByte.RefTypeIndex, 1)
		{
			_valueRef = value;
		}

		[global::System.Obsolete(global::UnionGen.InternalUtil.UnionGenInternalConst.DefaultConstructorWarning, true)]
		public StringOrException(): this(0, 0) {}

		public bool IsString
		{
			[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)] get => _state.ActualTypeIndex == 0;
		}
		public bool IsException
		{
			[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)] get => _state.ActualTypeIndex == 1;
		}

		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public string AsString() =>
			IsString
				? (string) _valueRef!
				: throw global::UnionGen.InternalUtil.ExceptionHelper.ThrowNotOfType(GetTypeName(0), GetTypeName(_state.ActualTypeIndex));
		
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public global::System.Exception AsException() =>
			IsException
				? (global::System.Exception) _valueRef!
				: throw global::UnionGen.InternalUtil.ExceptionHelper.ThrowNotOfType(GetTypeName(1), GetTypeName(_state.ActualTypeIndex));

		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public static implicit operator StringOrException(string value) => new StringOrException(value);
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public static implicit operator StringOrException(global::System.Exception value) => new StringOrException(value);
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public static bool operator ==(StringOrException left, StringOrException right) => left.Equals(right);
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public static bool operator !=(StringOrException left, StringOrException right) => !left.Equals(right);

		public TResult Match<TResult>(global::System.Func<string, TResult> withString, global::System.Func<global::System.Exception, TResult> withException) => 		
			_state.ActualTypeIndex switch
			{
				0 => withString((string)_valueRef!),
				1 => withException((global::System.Exception)_valueRef!),
				_ => throw global::UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(_state.ActualTypeIndex)
			};

		public async global::System.Threading.Tasks.ValueTask<TResult> MatchAsync<TResult>(global::System.Func<string, global::System.Threading.Tasks.ValueTask<TResult>> withString, global::System.Func<global::System.Exception, global::System.Threading.Tasks.ValueTask<TResult>> withException) => 		
			_state.ActualTypeIndex switch
			{
				0 => await withString((string)_valueRef!),
				1 => await withException((global::System.Exception)_valueRef!),
				_ => throw global::UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(_state.ActualTypeIndex)
			};

		public void Switch(global::System.Action<string> forString, global::System.Action<global::System.Exception> forException)		
		{
			switch (_state.ActualTypeIndex)
			{
				case 0: forString((string)_valueRef!); break;
				case 1: forException((global::System.Exception)_valueRef!); break;
				default: throw global::UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(_state.ActualTypeIndex);
			}
		}

		public async global::System.Threading.Tasks.ValueTask SwitchAsync(global::System.Func<string, global::System.Threading.Tasks.ValueTask> forString, global::System.Func<global::System.Exception, global::System.Threading.Tasks.ValueTask> forException)		
		{
			switch (_state.ActualTypeIndex)
			{
				case 0: await forString((string)_valueRef!); break;
				case 1: await forException((global::System.Exception)_valueRef!); break;
				default: throw global::UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(_state.ActualTypeIndex);
			}
		}

		public override string ToString() => 		
			_state.ActualTypeIndex switch
			{
				0 => _valueRef?.ToString() ?? global::UnionGen.InternalUtil.UnionGenInternalConst.NullString,
				1 => _valueRef?.ToString() ?? global::UnionGen.InternalUtil.UnionGenInternalConst.NullString,
				_ => throw global::UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(_state.ActualTypeIndex)
			};

		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public bool Equals(StringOrException other) => 
			_state.ActualTypeIndex == other._state.ActualTypeIndex
				&& _state.ActualTypeIndex switch 
				{
					0 => ReferenceEquals(_valueRef, other._valueRef) || (_valueRef?.Equals(other._valueRef) ?? false),
					1 => ReferenceEquals(_valueRef, other._valueRef) || (_valueRef?.Equals(other._valueRef) ?? false),
					_ => false
				};

		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public override bool Equals(object? obj)
		{
			if (ReferenceEquals(null, obj))
			{
				return false;
			}
			return obj is StringOrException other && Equals(other);
		}

		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public override int GetHashCode()
		{
			unchecked
			{
				var hash = _state.ActualTypeIndex switch
				{
					0 => _valueRef?.GetHashCode() ?? 0,
					1 => _valueRef?.GetHashCode() ?? 0,
					_ => 0
				};
				return (hash * 397) ^ _state.ActualTypeIndex;
			}
		}

		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public string GetTypeName(int index) =>
			index switch 
			{
				0 => "string",
				1 => "System.Exception",
				_ => throw global::UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(index)
			};

    }

}
