//HintName: Test.IntOrDouble.g.cs
// <auto-generated by UnionSourceGen />
#nullable enable
namespace Test
{

    public readonly partial struct IntOrDouble : global::System.IEquatable<IntOrDouble>
    {
		private readonly int _value0;
		private readonly double _value1;
		private readonly global::UnionGen.InternalUtil.StateByte _state;

		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		private IntOrDouble(int index, int actualTypeIndex)
		{
			_state = new global::UnionGen.InternalUtil.StateByte(index, actualTypeIndex);
		}

		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public IntOrDouble(int value): this(0, 0)
		{
			_value0 = value;
		}

		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public IntOrDouble(double value): this(1, 1)
		{
			_value1 = value;
		}

		[global::System.Obsolete(global::UnionGen.InternalUtil.UnionGenInternalConst.DefaultConstructorWarning, true)]
		public IntOrDouble(): this(0, 0) {}

		public bool IsInt
		{
			[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)] get => _state.ActualTypeIndex == 0;
		}
		public bool IsDouble
		{
			[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)] get => _state.ActualTypeIndex == 1;
		}

		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public int AsInt() =>
			IsInt
				? _value0
				: throw global::UnionGen.InternalUtil.ExceptionHelper.ThrowNotOfType(GetTypeName(0), GetTypeName(_state.ActualTypeIndex));
		
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public double AsDouble() =>
			IsDouble
				? _value1
				: throw global::UnionGen.InternalUtil.ExceptionHelper.ThrowNotOfType(GetTypeName(1), GetTypeName(_state.ActualTypeIndex));

		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public static implicit operator IntOrDouble(int value) => new IntOrDouble(value);
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public static implicit operator IntOrDouble(double value) => new IntOrDouble(value);
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public static bool operator ==(IntOrDouble left, IntOrDouble right) => left.Equals(right);
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public static bool operator !=(IntOrDouble left, IntOrDouble right) => !left.Equals(right);

		public TResult Match<TResult>(global::System.Func<int, TResult> withInt, global::System.Func<double, TResult> withDouble) => 		
			_state.ActualTypeIndex switch
			{
				0 => withInt(_value0),
				1 => withDouble(_value1),
				_ => throw global::UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(_state.ActualTypeIndex)
			};

		public async global::System.Threading.Tasks.ValueTask<TResult> MatchAsync<TResult>(global::System.Func<int, global::System.Threading.Tasks.ValueTask<TResult>> withInt, global::System.Func<double, global::System.Threading.Tasks.ValueTask<TResult>> withDouble) => 		
			_state.ActualTypeIndex switch
			{
				0 => await withInt(_value0),
				1 => await withDouble(_value1),
				_ => throw global::UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(_state.ActualTypeIndex)
			};

		public void Switch(global::System.Action<int> forInt, global::System.Action<double> forDouble)		
		{
			switch (_state.ActualTypeIndex)
			{
				case 0: forInt(_value0); break;
				case 1: forDouble(_value1); break;
				default: throw global::UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(_state.ActualTypeIndex);
			}
		}

		public async global::System.Threading.Tasks.ValueTask SwitchAsync(global::System.Func<int, global::System.Threading.Tasks.ValueTask> forInt, global::System.Func<double, global::System.Threading.Tasks.ValueTask> forDouble)		
		{
			switch (_state.ActualTypeIndex)
			{
				case 0: await forInt(_value0); break;
				case 1: await forDouble(_value1); break;
				default: throw global::UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(_state.ActualTypeIndex);
			}
		}

		public override string ToString() => 		
			_state.ActualTypeIndex switch
			{
				0 => _value0.ToString()!,
				1 => _value1.ToString()!,
				_ => throw global::UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(_state.ActualTypeIndex)
			};

		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public bool Equals(IntOrDouble other) => 
			_state.ActualTypeIndex == other._state.ActualTypeIndex
				&& _state.ActualTypeIndex switch 
				{
					0 => _value0.Equals(other._value0),
					1 => _value1.Equals(other._value1),
					_ => false
				};

		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public override bool Equals(object? obj)
		{
			if (ReferenceEquals(null, obj))
			{
				return false;
			}
			return obj is IntOrDouble other && Equals(other);
		}

		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public override int GetHashCode()
		{
			unchecked
			{
				var hash = _state.ActualTypeIndex switch
				{
					0 => _value0.GetHashCode(),
					1 => _value1.GetHashCode(),
					_ => 0
				};
				return (hash * 397) ^ _state.ActualTypeIndex;
			}
		}

		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public string GetTypeName(int index) =>
			index switch 
			{
				0 => "int",
				1 => "double",
				_ => throw global::UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(index)
			};

    }

}
