//HintName: Test.IntOrDouble.g.cs
// <auto-generated by UnionSourceGen />
#nullable enable
using System;
using System.Threading.Tasks;
namespace Test
{

    public readonly partial struct IntOrDouble : IEquatable<IntOrDouble>
    {
		private readonly int _value0;
		private readonly double _value1;
		private readonly UnionGen.InternalUtil.StateByte _state;

		private IntOrDouble(int index, int actualTypeIndex)
		{
			_state = new UnionGen.InternalUtil.StateByte(index, actualTypeIndex);
		}

		public IntOrDouble(int value): this(0, 0)
		{
			_value0 = value;
		}

		public IntOrDouble(double value): this(1, 1)
		{
			_value1 = value;
		}

		[Obsolete(UnionGen.InternalUtil.UnionGenInternalConst.DefaultConstructorWarning, true)]
		public IntOrDouble(): this(0, 0) {}

		public bool IsInt => _state.ActualTypeIndex == 0;
		public bool IsDouble => _state.ActualTypeIndex == 1;

		public int AsInt() =>
			IsInt
				? _value0
				: throw UnionGen.InternalUtil.ExceptionHelper.ThrowNotOfType(GetTypeName(0), GetTypeName(_state.ActualTypeIndex));
		
		public double AsDouble() =>
			IsDouble
				? _value1
				: throw UnionGen.InternalUtil.ExceptionHelper.ThrowNotOfType(GetTypeName(1), GetTypeName(_state.ActualTypeIndex));

		public static implicit operator IntOrDouble(int value) => new IntOrDouble(value);
		public static implicit operator IntOrDouble(double value) => new IntOrDouble(value);
		public static bool operator ==(IntOrDouble left, IntOrDouble right) => left.Equals(right);
		public static bool operator !=(IntOrDouble left, IntOrDouble right) => !left.Equals(right);

		public TResult Match<TResult>(Func<int, TResult> withInt, Func<double, TResult> withDouble) => 		
			_state.ActualTypeIndex switch
			{
				0 => withInt(_value0),
				1 => withDouble(_value1),
				_ => throw UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(_state.ActualTypeIndex)
			};

		public async ValueTask<TResult> MatchAsync<TResult>(Func<int, ValueTask<TResult>> withInt, Func<double, ValueTask<TResult>> withDouble) => 		
			_state.ActualTypeIndex switch
			{
				0 => await withInt(_value0),
				1 => await withDouble(_value1),
				_ => throw UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(_state.ActualTypeIndex)
			};

		public void Switch(Action<int> forInt, Action<double> forDouble)		
		{
			switch (_state.ActualTypeIndex)
			{
				case 0: forInt(_value0); break;
				case 1: forDouble(_value1); break;
				default: throw UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(_state.ActualTypeIndex);
			}
		}

		public async ValueTask SwitchAsync(Func<int, ValueTask> forInt, Func<double, ValueTask> forDouble)		
		{
			switch (_state.ActualTypeIndex)
			{
				case 0: await forInt(_value0); break;
				case 1: await forDouble(_value1); break;
				default: throw UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(_state.ActualTypeIndex);
			}
		}

		public override string ToString() => 		
			_state.ActualTypeIndex switch
			{
				0 => _value0.ToString()!,
				1 => _value1.ToString()!,
				_ => throw UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(_state.ActualTypeIndex)
			};

		public bool Equals(IntOrDouble other) => 
			_state.ActualTypeIndex == other._state.ActualTypeIndex
				&& _state.ActualTypeIndex switch 
				{
					0 => _value0.Equals(other._value0),
					1 => _value1.Equals(other._value1),
					_ => false
				};

		public override bool Equals(object? obj)
		{
			if (ReferenceEquals(null, obj))
			{
				return false;
			}
			return obj is IntOrDouble other && Equals(other);
		}

		public override int GetHashCode(){		
			unchecked
			{
				var hash = _state.ActualTypeIndex switch
				{
					0 => _value0.GetHashCode(),
					1 => _value1.GetHashCode(),
					_ => 0
				};
				return (hash * 397) ^ _state.ActualTypeIndex;
			}
		}

		public string GetTypeName(int index) =>
			index switch 
			{
				0 => "int",
				1 => "double",
				_ => throw UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(index)
			};

    }

}
