//HintName: Test.SuccessOrFailure.g.cs
// <auto-generated by UnionSourceGen />
#nullable enable
namespace Test
{

    public readonly partial struct SuccessOrFailure : global::System.IEquatable<SuccessOrFailure>
    {
		private readonly global::UnionGen.Types.Success<int> _value0;
		private readonly global::UnionGen.Types.Failure _value1;
		private readonly global::UnionGen.InternalUtil.StateByte _state;

		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		private SuccessOrFailure(int index, int actualTypeIndex)
		{
			_state = new global::UnionGen.InternalUtil.StateByte(index, actualTypeIndex);
		}

		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public SuccessOrFailure(global::UnionGen.Types.Success<int> value): this(0, 0)
		{
			_value0 = value;
		}

		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public SuccessOrFailure(global::UnionGen.Types.Failure value): this(1, 1)
		{
			_value1 = value;
		}

		[global::System.Obsolete(global::UnionGen.InternalUtil.UnionGenInternalConst.DefaultConstructorWarning, true)]
		public SuccessOrFailure(): this(0, 0) {}

		public bool IsSuccessOfInt
		{
			[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)] get => _state.ActualTypeIndex == 0;
		}
		public bool IsFailure
		{
			[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)] get => _state.ActualTypeIndex == 1;
		}

		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public global::UnionGen.Types.Success<int> AsSuccessOfInt() =>
			IsSuccessOfInt
				? _value0
				: throw global::UnionGen.InternalUtil.ExceptionHelper.ThrowNotOfType(GetTypeName(0), GetTypeName(_state.ActualTypeIndex));
		
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public global::UnionGen.Types.Failure AsFailure() =>
			IsFailure
				? _value1
				: throw global::UnionGen.InternalUtil.ExceptionHelper.ThrowNotOfType(GetTypeName(1), GetTypeName(_state.ActualTypeIndex));

		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public static implicit operator SuccessOrFailure(global::UnionGen.Types.Success<int> value) => new SuccessOrFailure(value);
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public static implicit operator SuccessOrFailure(global::UnionGen.Types.Failure value) => new SuccessOrFailure(value);
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public static bool operator ==(SuccessOrFailure left, SuccessOrFailure right) => left.Equals(right);
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public static bool operator !=(SuccessOrFailure left, SuccessOrFailure right) => !left.Equals(right);

		public TResult Match<TResult>(global::System.Func<global::UnionGen.Types.Success<int>, TResult> withSuccessOfInt, global::System.Func<global::UnionGen.Types.Failure, TResult> withFailure) => 		
			_state.ActualTypeIndex switch
			{
				0 => withSuccessOfInt(_value0),
				1 => withFailure(_value1),
				_ => throw global::UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(_state.ActualTypeIndex)
			};

		public async global::System.Threading.Tasks.ValueTask<TResult> MatchAsync<TResult>(global::System.Func<global::UnionGen.Types.Success<int>, global::System.Threading.Tasks.ValueTask<TResult>> withSuccessOfInt, global::System.Func<global::UnionGen.Types.Failure, global::System.Threading.Tasks.ValueTask<TResult>> withFailure) => 		
			_state.ActualTypeIndex switch
			{
				0 => await withSuccessOfInt(_value0),
				1 => await withFailure(_value1),
				_ => throw global::UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(_state.ActualTypeIndex)
			};

		public void Switch(global::System.Action<global::UnionGen.Types.Success<int>> forSuccessOfInt, global::System.Action<global::UnionGen.Types.Failure> forFailure)		
		{
			switch (_state.ActualTypeIndex)
			{
				case 0: forSuccessOfInt(_value0); break;
				case 1: forFailure(_value1); break;
				default: throw global::UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(_state.ActualTypeIndex);
			}
		}

		public async global::System.Threading.Tasks.ValueTask SwitchAsync(global::System.Func<global::UnionGen.Types.Success<int>, global::System.Threading.Tasks.ValueTask> forSuccessOfInt, global::System.Func<global::UnionGen.Types.Failure, global::System.Threading.Tasks.ValueTask> forFailure)		
		{
			switch (_state.ActualTypeIndex)
			{
				case 0: await forSuccessOfInt(_value0); break;
				case 1: await forFailure(_value1); break;
				default: throw global::UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(_state.ActualTypeIndex);
			}
		}

		public override string ToString() => 		
			_state.ActualTypeIndex switch
			{
				0 => _value0.ToString()!,
				1 => _value1.ToString()!,
				_ => throw global::UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(_state.ActualTypeIndex)
			};

		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public bool Equals(SuccessOrFailure other) => 
			_state.ActualTypeIndex == other._state.ActualTypeIndex
				&& _state.ActualTypeIndex switch 
				{
					0 => _value0.Equals(other._value0),
					1 => _value1.Equals(other._value1),
					_ => false
				};

		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public override bool Equals(object? obj)
		{
			if (ReferenceEquals(null, obj))
			{
				return false;
			}
			return obj is SuccessOrFailure other && Equals(other);
		}

		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public override int GetHashCode()
		{
			unchecked
			{
				var hash = _state.ActualTypeIndex switch
				{
					0 => _value0.GetHashCode(),
					1 => _value1.GetHashCode(),
					_ => 0
				};
				return (hash * 397) ^ _state.ActualTypeIndex;
			}
		}

		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public string GetTypeName(int index) =>
			index switch 
			{
				0 => "UnionGen.Types.Success<int>",
				1 => "UnionGen.Types.Failure",
				_ => throw global::UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(index)
			};

    }

}
