//HintName: Test.ListOrLong.g.cs
// <auto-generated by UnionSourceGen />
#nullable enable
namespace Test
{

    public readonly partial struct ListOrLong : global::System.IEquatable<ListOrLong>
    {
		private readonly object? _valueRef;
		private readonly long _value1;
		private readonly global::UnionGen.InternalUtil.StateByte _state;

		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		private ListOrLong(int index, int actualTypeIndex)
		{
			_state = new global::UnionGen.InternalUtil.StateByte(index, actualTypeIndex);
		}

		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public ListOrLong(global::System.Collections.Generic.IList<int> value): this(global::UnionGen.InternalUtil.StateByte.RefTypeIndex, 0)
		{
			_valueRef = value;
		}

		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public ListOrLong(long value): this(1, 1)
		{
			_value1 = value;
		}

		[global::System.Obsolete(global::UnionGen.InternalUtil.UnionGenInternalConst.DefaultConstructorWarning, true)]
		public ListOrLong(): this(0, 0) {}

		public bool IsIListOfInt
		{
			[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)] get => _state.ActualTypeIndex == 0;
		}
		public bool IsLong
		{
			[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)] get => _state.ActualTypeIndex == 1;
		}

		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public global::System.Collections.Generic.IList<int> AsIListOfInt() =>
			IsIListOfInt
				? (global::System.Collections.Generic.IList<int>) _valueRef!
				: throw global::UnionGen.InternalUtil.ExceptionHelper.ThrowNotOfType(GetTypeName(0), GetTypeName(_state.ActualTypeIndex));
		
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public long AsLong() =>
			IsLong
				? _value1
				: throw global::UnionGen.InternalUtil.ExceptionHelper.ThrowNotOfType(GetTypeName(1), GetTypeName(_state.ActualTypeIndex));

		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public static implicit operator ListOrLong(long value) => new ListOrLong(value);
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public static bool operator ==(ListOrLong left, ListOrLong right) => left.Equals(right);
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public static bool operator !=(ListOrLong left, ListOrLong right) => !left.Equals(right);

		public TResult Match<TResult>(global::System.Func<global::System.Collections.Generic.IList<int>, TResult> withIListOfInt, global::System.Func<long, TResult> withLong) => 		
			_state.ActualTypeIndex switch
			{
				0 => withIListOfInt((global::System.Collections.Generic.IList<int>)_valueRef!),
				1 => withLong(_value1),
				_ => throw global::UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(_state.ActualTypeIndex)
			};

		public async global::System.Threading.Tasks.ValueTask<TResult> MatchAsync<TResult>(global::System.Func<global::System.Collections.Generic.IList<int>, global::System.Threading.Tasks.ValueTask<TResult>> withIListOfInt, global::System.Func<long, global::System.Threading.Tasks.ValueTask<TResult>> withLong) => 		
			_state.ActualTypeIndex switch
			{
				0 => await withIListOfInt((global::System.Collections.Generic.IList<int>)_valueRef!),
				1 => await withLong(_value1),
				_ => throw global::UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(_state.ActualTypeIndex)
			};

		public void Switch(global::System.Action<global::System.Collections.Generic.IList<int>> forIListOfInt, global::System.Action<long> forLong)		
		{
			switch (_state.ActualTypeIndex)
			{
				case 0: forIListOfInt((global::System.Collections.Generic.IList<int>)_valueRef!); break;
				case 1: forLong(_value1); break;
				default: throw global::UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(_state.ActualTypeIndex);
			}
		}

		public async global::System.Threading.Tasks.ValueTask SwitchAsync(global::System.Func<global::System.Collections.Generic.IList<int>, global::System.Threading.Tasks.ValueTask> forIListOfInt, global::System.Func<long, global::System.Threading.Tasks.ValueTask> forLong)		
		{
			switch (_state.ActualTypeIndex)
			{
				case 0: await forIListOfInt((global::System.Collections.Generic.IList<int>)_valueRef!); break;
				case 1: await forLong(_value1); break;
				default: throw global::UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(_state.ActualTypeIndex);
			}
		}

		public override string ToString() => 		
			_state.ActualTypeIndex switch
			{
				0 => _valueRef?.ToString() ?? global::UnionGen.InternalUtil.UnionGenInternalConst.NullString,
				1 => _value1.ToString()!,
				_ => throw global::UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(_state.ActualTypeIndex)
			};

		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public bool Equals(ListOrLong other) => 
			_state.ActualTypeIndex == other._state.ActualTypeIndex
				&& _state.ActualTypeIndex switch 
				{
					0 => ReferenceEquals(_valueRef, other._valueRef) || (_valueRef?.Equals(other._valueRef) ?? false),
					1 => _value1.Equals(other._value1),
					_ => false
				};

		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public override bool Equals(object? obj)
		{
			if (ReferenceEquals(null, obj))
			{
				return false;
			}
			return obj is ListOrLong other && Equals(other);
		}

		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public override int GetHashCode()
		{
			unchecked
			{
				var hash = _state.ActualTypeIndex switch
				{
					0 => _valueRef?.GetHashCode() ?? 0,
					1 => _value1.GetHashCode(),
					_ => 0
				};
				return (hash * 397) ^ _state.ActualTypeIndex;
			}
		}

		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public string GetTypeName(int index) =>
			index switch 
			{
				0 => "System.Collections.Generic.IList<int>",
				1 => "long",
				_ => throw global::UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(index)
			};

    }

}
