//HintName: Test.IntOrLongArray.g.cs
// <auto-generated by UnionSourceGen />
#nullable enable
namespace Test
{

    public readonly partial struct IntOrLongArray : global::System.IEquatable<IntOrLongArray>
    {
		private readonly object? _valueRef;
		private readonly int _value0;
		private readonly global::UnionGen.InternalUtil.StateByte _state;

		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		private IntOrLongArray(int index, int actualTypeIndex)
		{
			_state = new global::UnionGen.InternalUtil.StateByte(index, actualTypeIndex);
		}

		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public IntOrLongArray(int value): this(0, 0)
		{
			_value0 = value;
		}

		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public IntOrLongArray(long[] value): this(global::UnionGen.InternalUtil.StateByte.RefTypeIndex, 1)
		{
			_valueRef = value;
		}

		[global::System.Obsolete(global::UnionGen.InternalUtil.UnionGenInternalConst.DefaultConstructorWarning, true)]
		public IntOrLongArray(): this(0, 0) {}

		public bool IsInt
		{
			[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)] get => _state.ActualTypeIndex == 0;
		}
		public bool IsLongArray
		{
			[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)] get => _state.ActualTypeIndex == 1;
		}

		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public int AsInt() =>
			IsInt
				? _value0
				: throw global::UnionGen.InternalUtil.ExceptionHelper.ThrowNotOfType(GetTypeName(0), GetTypeName(_state.ActualTypeIndex));
		
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public long[] AsLongArray() =>
			IsLongArray
				? (long[]) _valueRef!
				: throw global::UnionGen.InternalUtil.ExceptionHelper.ThrowNotOfType(GetTypeName(1), GetTypeName(_state.ActualTypeIndex));

		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public static implicit operator IntOrLongArray(int value) => new IntOrLongArray(value);
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public static implicit operator IntOrLongArray(long[] value) => new IntOrLongArray(value);
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public static bool operator ==(IntOrLongArray left, IntOrLongArray right) => left.Equals(right);
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public static bool operator !=(IntOrLongArray left, IntOrLongArray right) => !left.Equals(right);

		public TResult Match<TResult>(global::System.Func<int, TResult> withInt, global::System.Func<long[], TResult> withLongArray) => 		
			_state.ActualTypeIndex switch
			{
				0 => withInt(_value0),
				1 => withLongArray((long[])_valueRef!),
				_ => throw global::UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(_state.ActualTypeIndex)
			};

		public async global::System.Threading.Tasks.ValueTask<TResult> MatchAsync<TResult>(global::System.Func<int, global::System.Threading.Tasks.ValueTask<TResult>> withInt, global::System.Func<long[], global::System.Threading.Tasks.ValueTask<TResult>> withLongArray) => 		
			_state.ActualTypeIndex switch
			{
				0 => await withInt(_value0),
				1 => await withLongArray((long[])_valueRef!),
				_ => throw global::UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(_state.ActualTypeIndex)
			};

		public void Switch(global::System.Action<int> forInt, global::System.Action<long[]> forLongArray)		
		{
			switch (_state.ActualTypeIndex)
			{
				case 0: forInt(_value0); break;
				case 1: forLongArray((long[])_valueRef!); break;
				default: throw global::UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(_state.ActualTypeIndex);
			}
		}

		public async global::System.Threading.Tasks.ValueTask SwitchAsync(global::System.Func<int, global::System.Threading.Tasks.ValueTask> forInt, global::System.Func<long[], global::System.Threading.Tasks.ValueTask> forLongArray)		
		{
			switch (_state.ActualTypeIndex)
			{
				case 0: await forInt(_value0); break;
				case 1: await forLongArray((long[])_valueRef!); break;
				default: throw global::UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(_state.ActualTypeIndex);
			}
		}

		public override string ToString() => 		
			_state.ActualTypeIndex switch
			{
				0 => _value0.ToString()!,
				1 => _valueRef?.ToString() ?? global::UnionGen.InternalUtil.UnionGenInternalConst.NullString,
				_ => throw global::UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(_state.ActualTypeIndex)
			};

		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public bool Equals(IntOrLongArray other) => 
			_state.ActualTypeIndex == other._state.ActualTypeIndex
				&& _state.ActualTypeIndex switch 
				{
					0 => _value0.Equals(other._value0),
					1 => ReferenceEquals(_valueRef, other._valueRef) || (_valueRef?.Equals(other._valueRef) ?? false),
					_ => false
				};

		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public override bool Equals(object? obj)
		{
			if (ReferenceEquals(null, obj))
			{
				return false;
			}
			return obj is IntOrLongArray other && Equals(other);
		}

		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public override int GetHashCode()
		{
			unchecked
			{
				var hash = _state.ActualTypeIndex switch
				{
					0 => _value0.GetHashCode(),
					1 => _valueRef?.GetHashCode() ?? 0,
					_ => 0
				};
				return (hash * 397) ^ _state.ActualTypeIndex;
			}
		}

		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public string GetTypeName(int index) =>
			index switch 
			{
				0 => "int",
				1 => "long[]",
				_ => throw global::UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(index)
			};

    }

}
