//HintName: Test.IOuter.Nested.g.cs
// <auto-generated by UnionSourceGen />
#nullable enable
namespace Test
{
public partial interface IOuter {

    public readonly partial struct Nested : global::System.IEquatable<Nested>
    {
		private readonly int _value0;
		private readonly double _value1;
		private readonly long _value2;
		private readonly global::UnionGen.InternalUtil.StateByte _state;

		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		private Nested(int index, int actualTypeIndex)
		{
			_state = new global::UnionGen.InternalUtil.StateByte(index, actualTypeIndex);
		}

		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public Nested(int value): this(0, 0)
		{
			_value0 = value;
		}

		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public Nested(double value): this(1, 1)
		{
			_value1 = value;
		}

		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public Nested(long value): this(2, 2)
		{
			_value2 = value;
		}

		[global::System.Obsolete(global::UnionGen.InternalUtil.UnionGenInternalConst.DefaultConstructorWarning, true)]
		public Nested(): this(0, 0) {}

		public bool IsInt
		{
			[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)] get => _state.ActualTypeIndex == 0;
		}
		public bool IsDouble
		{
			[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)] get => _state.ActualTypeIndex == 1;
		}
		public bool IsLong
		{
			[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)] get => _state.ActualTypeIndex == 2;
		}

		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public int AsInt() =>
			IsInt
				? _value0
				: throw global::UnionGen.InternalUtil.ExceptionHelper.ThrowNotOfType(GetTypeName(0), GetTypeName(_state.ActualTypeIndex));
		
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public double AsDouble() =>
			IsDouble
				? _value1
				: throw global::UnionGen.InternalUtil.ExceptionHelper.ThrowNotOfType(GetTypeName(1), GetTypeName(_state.ActualTypeIndex));
		
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public long AsLong() =>
			IsLong
				? _value2
				: throw global::UnionGen.InternalUtil.ExceptionHelper.ThrowNotOfType(GetTypeName(2), GetTypeName(_state.ActualTypeIndex));

		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public static implicit operator Nested(int value) => new Nested(value);
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public static implicit operator Nested(double value) => new Nested(value);
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public static implicit operator Nested(long value) => new Nested(value);
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public static bool operator ==(Nested left, Nested right) => left.Equals(right);
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public static bool operator !=(Nested left, Nested right) => !left.Equals(right);

		public TResult Match<TResult>(global::System.Func<int, TResult> withInt, global::System.Func<double, TResult> withDouble, global::System.Func<long, TResult> withLong) => 		
			_state.ActualTypeIndex switch
			{
				0 => withInt(_value0),
				1 => withDouble(_value1),
				2 => withLong(_value2),
				_ => throw global::UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(_state.ActualTypeIndex)
			};

		public async global::System.Threading.Tasks.ValueTask<TResult> MatchAsync<TResult>(global::System.Func<int, global::System.Threading.Tasks.ValueTask<TResult>> withInt, global::System.Func<double, global::System.Threading.Tasks.ValueTask<TResult>> withDouble, global::System.Func<long, global::System.Threading.Tasks.ValueTask<TResult>> withLong) => 		
			_state.ActualTypeIndex switch
			{
				0 => await withInt(_value0),
				1 => await withDouble(_value1),
				2 => await withLong(_value2),
				_ => throw global::UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(_state.ActualTypeIndex)
			};

		public void Switch(global::System.Action<int> forInt, global::System.Action<double> forDouble, global::System.Action<long> forLong)		
		{
			switch (_state.ActualTypeIndex)
			{
				case 0: forInt(_value0); break;
				case 1: forDouble(_value1); break;
				case 2: forLong(_value2); break;
				default: throw global::UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(_state.ActualTypeIndex);
			}
		}

		public async global::System.Threading.Tasks.ValueTask SwitchAsync(global::System.Func<int, global::System.Threading.Tasks.ValueTask> forInt, global::System.Func<double, global::System.Threading.Tasks.ValueTask> forDouble, global::System.Func<long, global::System.Threading.Tasks.ValueTask> forLong)		
		{
			switch (_state.ActualTypeIndex)
			{
				case 0: await forInt(_value0); break;
				case 1: await forDouble(_value1); break;
				case 2: await forLong(_value2); break;
				default: throw global::UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(_state.ActualTypeIndex);
			}
		}

		public override string ToString() => 		
			_state.ActualTypeIndex switch
			{
				0 => _value0.ToString()!,
				1 => _value1.ToString()!,
				2 => _value2.ToString()!,
				_ => throw global::UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(_state.ActualTypeIndex)
			};

		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public bool Equals(Nested other) => 
			_state.ActualTypeIndex == other._state.ActualTypeIndex
				&& _state.ActualTypeIndex switch 
				{
					0 => _value0.Equals(other._value0),
					1 => _value1.Equals(other._value1),
					2 => _value2.Equals(other._value2),
					_ => false
				};

		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public override bool Equals(object? obj)
		{
			if (ReferenceEquals(null, obj))
			{
				return false;
			}
			return obj is Nested other && Equals(other);
		}

		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public override int GetHashCode()
		{
			unchecked
			{
				var hash = _state.ActualTypeIndex switch
				{
					0 => _value0.GetHashCode(),
					1 => _value1.GetHashCode(),
					2 => _value2.GetHashCode(),
					_ => 0
				};
				return (hash * 397) ^ _state.ActualTypeIndex;
			}
		}

		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public string GetTypeName(int index) =>
			index switch 
			{
				0 => "int",
				1 => "double",
				2 => "long",
				_ => throw global::UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(index)
			};

    }
}

}
