//HintName: Test.ListOrLong.g.cs
// <auto-generated by UnionSourceGen />
#nullable enable
using System;
using System.Threading.Tasks;
namespace Test
{

    public readonly partial struct ListOrLong : IEquatable<ListOrLong>
    {
		private readonly object? _valueRef;
		private readonly long _value1;
		private readonly UnionGen.InternalUtil.StateByte _state;

		private ListOrLong(int index, int actualTypeIndex)
		{
			_state = new UnionGen.InternalUtil.StateByte(index, actualTypeIndex);
		}

		public ListOrLong(System.Collections.Generic.IList<int> value): this(UnionGen.InternalUtil.StateByte.RefTypeIndex, 0)
		{
			_valueRef = value;
		}

		public ListOrLong(long value): this(1, 1)
		{
			_value1 = value;
		}

		[Obsolete(UnionGen.InternalUtil.UnionGenInternalConst.DefaultConstructorWarning, true)]
		public ListOrLong(): this(0, 0) {}

		public bool IsIListOfInt => _state.ActualTypeIndex == 0;
		public bool IsLong => _state.ActualTypeIndex == 1;

		public System.Collections.Generic.IList<int> AsIListOfInt() =>
			IsIListOfInt
				? (System.Collections.Generic.IList<int>) _valueRef!
				: throw UnionGen.InternalUtil.ExceptionHelper.ThrowNotOfType(GetTypeName(0), GetTypeName(_state.ActualTypeIndex));
		
		public long AsLong() =>
			IsLong
				? _value1
				: throw UnionGen.InternalUtil.ExceptionHelper.ThrowNotOfType(GetTypeName(1), GetTypeName(_state.ActualTypeIndex));

		public static implicit operator ListOrLong(long value) => new ListOrLong(value);
		public static bool operator ==(ListOrLong left, ListOrLong right) => left.Equals(right);
		public static bool operator !=(ListOrLong left, ListOrLong right) => !left.Equals(right);

		public TResult Match<TResult>(Func<System.Collections.Generic.IList<int>, TResult> withIListOfInt, Func<long, TResult> withLong) => 		
			_state.ActualTypeIndex switch
			{
				0 => withIListOfInt((System.Collections.Generic.IList<int>)_valueRef!),
				1 => withLong(_value1),
				_ => throw UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(_state.ActualTypeIndex)
			};

		public async ValueTask<TResult> MatchAsync<TResult>(Func<System.Collections.Generic.IList<int>, ValueTask<TResult>> withIListOfInt, Func<long, ValueTask<TResult>> withLong) => 		
			_state.ActualTypeIndex switch
			{
				0 => await withIListOfInt((System.Collections.Generic.IList<int>)_valueRef!),
				1 => await withLong(_value1),
				_ => throw UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(_state.ActualTypeIndex)
			};

		public void Switch(Action<System.Collections.Generic.IList<int>> forIListOfInt, Action<long> forLong)		
		{
			switch (_state.ActualTypeIndex)
			{
				case 0: forIListOfInt((System.Collections.Generic.IList<int>)_valueRef!); break;
				case 1: forLong(_value1); break;
				default: throw UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(_state.ActualTypeIndex);
			}
		}

		public async ValueTask SwitchAsync(Func<System.Collections.Generic.IList<int>, ValueTask> forIListOfInt, Func<long, ValueTask> forLong)		
		{
			switch (_state.ActualTypeIndex)
			{
				case 0: await forIListOfInt((System.Collections.Generic.IList<int>)_valueRef!); break;
				case 1: await forLong(_value1); break;
				default: throw UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(_state.ActualTypeIndex);
			}
		}

		public override string ToString() => 		
			_state.ActualTypeIndex switch
			{
				0 => _valueRef?.ToString() ?? UnionGen.InternalUtil.UnionGenInternalConst.NullString,
				1 => _value1.ToString()!,
				_ => throw UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(_state.ActualTypeIndex)
			};

		public bool Equals(ListOrLong other) => 
			_state.ActualTypeIndex == other._state.ActualTypeIndex
				&& _state.ActualTypeIndex switch 
				{
					0 => ReferenceEquals(_valueRef, other._valueRef) || (_valueRef?.Equals(other._valueRef) ?? false),
					1 => _value1.Equals(other._value1),
					_ => false
				};

		public override bool Equals(object? obj)
		{
			if (ReferenceEquals(null, obj))
			{
				return false;
			}
			return obj is ListOrLong other && Equals(other);
		}

		public override int GetHashCode(){		
			unchecked
			{
				var hash = _state.ActualTypeIndex switch
				{
					0 => _valueRef?.GetHashCode() ?? 0,
					1 => _value1.GetHashCode(),
					_ => 0
				};
				return (hash * 397) ^ _state.ActualTypeIndex;
			}
		}

		public string GetTypeName(int index) =>
			index switch 
			{
				0 => "System.Collections.Generic.IList<int>",
				1 => "long",
				_ => throw UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(index)
			};

    }

}
