//HintName: Test.StringOrException.g.cs
// <auto-generated by UnionSourceGen />
#nullable enable
using System;
using System.Threading.Tasks;
namespace Test
{

    public readonly partial struct StringOrException : IEquatable<StringOrException>
    {
		private readonly object? _valueRef;
		private readonly UnionGen.InternalUtil.StateByte _state;

		private StringOrException(int index, int actualTypeIndex)
		{
			_state = new UnionGen.InternalUtil.StateByte(index, actualTypeIndex);
		}

		public StringOrException(string value): this(UnionGen.InternalUtil.StateByte.RefTypeIndex, 0)
		{
			_valueRef = value;
		}

		public StringOrException(System.Exception value): this(UnionGen.InternalUtil.StateByte.RefTypeIndex, 1)
		{
			_valueRef = value;
		}

		[Obsolete(UnionGen.InternalUtil.UnionGenInternalConst.DefaultConstructorWarning, true)]
		public StringOrException(): this(0, 0) {}

		public bool IsString => _state.ActualTypeIndex == 0;
		public bool IsException => _state.ActualTypeIndex == 1;

		public string AsString() =>
			IsString
				? (string) _valueRef!
				: throw UnionGen.InternalUtil.ExceptionHelper.ThrowNotOfType(GetTypeName(0), GetTypeName(_state.ActualTypeIndex));
		
		public System.Exception AsException() =>
			IsException
				? (System.Exception) _valueRef!
				: throw UnionGen.InternalUtil.ExceptionHelper.ThrowNotOfType(GetTypeName(1), GetTypeName(_state.ActualTypeIndex));

		public static implicit operator StringOrException(string value) => new StringOrException(value);
		public static implicit operator StringOrException(System.Exception value) => new StringOrException(value);
		public static bool operator ==(StringOrException left, StringOrException right) => left.Equals(right);
		public static bool operator !=(StringOrException left, StringOrException right) => !left.Equals(right);

		public TResult Match<TResult>(Func<string, TResult> withString, Func<System.Exception, TResult> withException) => 		
			_state.ActualTypeIndex switch
			{
				0 => withString((string)_valueRef!),
				1 => withException((System.Exception)_valueRef!),
				_ => throw UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(_state.ActualTypeIndex)
			};

		public async ValueTask<TResult> MatchAsync<TResult>(Func<string, ValueTask<TResult>> withString, Func<System.Exception, ValueTask<TResult>> withException) => 		
			_state.ActualTypeIndex switch
			{
				0 => await withString((string)_valueRef!),
				1 => await withException((System.Exception)_valueRef!),
				_ => throw UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(_state.ActualTypeIndex)
			};

		public void Switch(Action<string> forString, Action<System.Exception> forException)		
		{
			switch (_state.ActualTypeIndex)
			{
				case 0: forString((string)_valueRef!); break;
				case 1: forException((System.Exception)_valueRef!); break;
				default: throw UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(_state.ActualTypeIndex);
			}
		}

		public async ValueTask SwitchAsync(Func<string, ValueTask> forString, Func<System.Exception, ValueTask> forException)		
		{
			switch (_state.ActualTypeIndex)
			{
				case 0: await forString((string)_valueRef!); break;
				case 1: await forException((System.Exception)_valueRef!); break;
				default: throw UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(_state.ActualTypeIndex);
			}
		}

		public override string ToString() => 		
			_state.ActualTypeIndex switch
			{
				0 => _valueRef?.ToString() ?? UnionGen.InternalUtil.UnionGenInternalConst.NullString,
				1 => _valueRef?.ToString() ?? UnionGen.InternalUtil.UnionGenInternalConst.NullString,
				_ => throw UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(_state.ActualTypeIndex)
			};

		public bool Equals(StringOrException other) => 
			_state.ActualTypeIndex == other._state.ActualTypeIndex
				&& _state.ActualTypeIndex switch 
				{
					0 => ReferenceEquals(_valueRef, other._valueRef) || (_valueRef?.Equals(other._valueRef) ?? false),
					1 => ReferenceEquals(_valueRef, other._valueRef) || (_valueRef?.Equals(other._valueRef) ?? false),
					_ => false
				};

		public override bool Equals(object? obj)
		{
			if (ReferenceEquals(null, obj))
			{
				return false;
			}
			return obj is StringOrException other && Equals(other);
		}

		public override int GetHashCode(){		
			unchecked
			{
				var hash = _state.ActualTypeIndex switch
				{
					0 => _valueRef?.GetHashCode() ?? 0,
					1 => _valueRef?.GetHashCode() ?? 0,
					_ => 0
				};
				return (hash * 397) ^ _state.ActualTypeIndex;
			}
		}

		public string GetTypeName(int index) =>
			index switch 
			{
				0 => "string",
				1 => "System.Exception",
				_ => throw UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(index)
			};

    }

}
