//HintName: Test.SuccessOrFailure.g.cs
// <auto-generated by UnionSourceGen />
#nullable enable
using System;
using System.Threading.Tasks;
namespace Test
{

    public readonly partial struct SuccessOrFailure : IEquatable<SuccessOrFailure>
    {
		private readonly UnionGen.Types.Success<int> _value0;
		private readonly UnionGen.Types.Failure _value1;
		private readonly UnionGen.InternalUtil.StateByte _state;

		private SuccessOrFailure(int index, int actualTypeIndex)
		{
			_state = new UnionGen.InternalUtil.StateByte(index, actualTypeIndex);
		}

		public SuccessOrFailure(UnionGen.Types.Success<int> value): this(0, 0)
		{
			_value0 = value;
		}

		public SuccessOrFailure(UnionGen.Types.Failure value): this(1, 1)
		{
			_value1 = value;
		}

		[Obsolete(UnionGen.InternalUtil.UnionGenInternalConst.DefaultConstructorWarning, true)]
		public SuccessOrFailure(): this(0, 0) {}

		public bool IsSuccessOfInt => _state.ActualTypeIndex == 0;
		public bool IsFailure => _state.ActualTypeIndex == 1;

		public UnionGen.Types.Success<int> AsSuccessOfInt() =>
			IsSuccessOfInt
				? _value0
				: throw UnionGen.InternalUtil.ExceptionHelper.ThrowNotOfType(GetTypeName(0), GetTypeName(_state.ActualTypeIndex));
		
		public UnionGen.Types.Failure AsFailure() =>
			IsFailure
				? _value1
				: throw UnionGen.InternalUtil.ExceptionHelper.ThrowNotOfType(GetTypeName(1), GetTypeName(_state.ActualTypeIndex));

		public static implicit operator SuccessOrFailure(UnionGen.Types.Success<int> value) => new SuccessOrFailure(value);
		public static implicit operator SuccessOrFailure(UnionGen.Types.Failure value) => new SuccessOrFailure(value);
		public static bool operator ==(SuccessOrFailure left, SuccessOrFailure right) => left.Equals(right);
		public static bool operator !=(SuccessOrFailure left, SuccessOrFailure right) => !left.Equals(right);

		public TResult Match<TResult>(Func<UnionGen.Types.Success<int>, TResult> withSuccessOfInt, Func<UnionGen.Types.Failure, TResult> withFailure) => 		
			_state.ActualTypeIndex switch
			{
				0 => withSuccessOfInt(_value0),
				1 => withFailure(_value1),
				_ => throw UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(_state.ActualTypeIndex)
			};

		public async ValueTask<TResult> MatchAsync<TResult>(Func<UnionGen.Types.Success<int>, ValueTask<TResult>> withSuccessOfInt, Func<UnionGen.Types.Failure, ValueTask<TResult>> withFailure) => 		
			_state.ActualTypeIndex switch
			{
				0 => await withSuccessOfInt(_value0),
				1 => await withFailure(_value1),
				_ => throw UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(_state.ActualTypeIndex)
			};

		public void Switch(Action<UnionGen.Types.Success<int>> forSuccessOfInt, Action<UnionGen.Types.Failure> forFailure)		
		{
			switch (_state.ActualTypeIndex)
			{
				case 0: forSuccessOfInt(_value0); break;
				case 1: forFailure(_value1); break;
				default: throw UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(_state.ActualTypeIndex);
			}
		}

		public async ValueTask SwitchAsync(Func<UnionGen.Types.Success<int>, ValueTask> forSuccessOfInt, Func<UnionGen.Types.Failure, ValueTask> forFailure)		
		{
			switch (_state.ActualTypeIndex)
			{
				case 0: await forSuccessOfInt(_value0); break;
				case 1: await forFailure(_value1); break;
				default: throw UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(_state.ActualTypeIndex);
			}
		}

		public override string ToString() => 		
			_state.ActualTypeIndex switch
			{
				0 => _value0.ToString()!,
				1 => _value1.ToString()!,
				_ => throw UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(_state.ActualTypeIndex)
			};

		public bool Equals(SuccessOrFailure other) => 
			_state.ActualTypeIndex == other._state.ActualTypeIndex
				&& _state.ActualTypeIndex switch 
				{
					0 => _value0.Equals(other._value0),
					1 => _value1.Equals(other._value1),
					_ => false
				};

		public override bool Equals(object? obj)
		{
			if (ReferenceEquals(null, obj))
			{
				return false;
			}
			return obj is SuccessOrFailure other && Equals(other);
		}

		public override int GetHashCode(){		
			unchecked
			{
				var hash = _state.ActualTypeIndex switch
				{
					0 => _value0.GetHashCode(),
					1 => _value1.GetHashCode(),
					_ => 0
				};
				return (hash * 397) ^ _state.ActualTypeIndex;
			}
		}

		public string GetTypeName(int index) =>
			index switch 
			{
				0 => "UnionGen.Types.Success<int>",
				1 => "UnionGen.Types.Failure",
				_ => throw UnionGen.InternalUtil.ExceptionHelper.ThrowUnknownTypeIndex(index)
			};

    }

}
