using System.Collections.Immutable;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace UnionGen;

[Generator]
public sealed class UnionSourceGen : IIncrementalGenerator
{
    internal const string AutoGeneratedComment = $"// <auto-generated by {nameof(UnionSourceGen)} />";
    private const string AttributeName = "UnionAttribute";
    private const int MinTypeParameters = 2;
    // this must not exceed 14 (we are storing the index in the lower four bits of a byte and need 15 for ref types)
    private const int MaxTypeParameters = 6;
    private const int NumberOfAttributes = MaxTypeParameters - MinTypeParameters + 1;

    private static readonly string[] attributeClasses;
    private static readonly Regex nameFromFullNameRegex = new(@"^.*\.(\D[\d\D]*)$", RegexOptions.Compiled);

    // Fully-qualified with a global:: prefix so the generated code can never be broken by a
    // consumer type that collides with a namespace we reference. Special types stay as keywords
    // (int, string, byte[]) for readability; they cannot be shadowed anyway.
    private static readonly SymbolDisplayFormat globalQualifiedFormat =
        SymbolDisplayFormat.FullyQualifiedFormat
                           .WithMiscellaneousOptions(SymbolDisplayMiscellaneousOptions.UseSpecialTypes
                                                     | SymbolDisplayMiscellaneousOptions.EscapeKeywordIdentifiers);

    static UnionSourceGen()
    {
        var genNamespace = typeof(UnionSourceGen).Namespace
                           ?? throw new InvalidOperationException("Namespace not found");
        attributeClasses = CreateAttributeClasses(genNamespace);
    }

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var unionsToGenerate = new List<IncrementalValuesProvider<UnionToGenerate?>>(NumberOfAttributes);

        foreach (var attributeClass in attributeClasses)
        {
            var unions = context.SyntaxProvider
                                .ForAttributeWithMetadataName(attributeClass,
                                                              static (node, _) => node is StructDeclarationSyntax,
                                                              static (ctx, _) => GetUnionToGenerate(ctx))
                                .Where(static m => m is not null);
            unionsToGenerate.Add(unions);
        }

        foreach (var unions in unionsToGenerate)
        {
            context.RegisterSourceOutput(unions, static (spc, source) => Execute(source, spc));
        }
    }

    private static string[] CreateAttributeClasses(string ns)
    {
        var attributeTypeNames = new List<string>(NumberOfAttributes);
        for (var i = MinTypeParameters; i <= MaxTypeParameters; i++)
        {
            attributeTypeNames.Add($"{ns}.{AttributeName}`{i}");
        }

        return attributeTypeNames.ToArray();
    }

    private static void Execute(UnionToGenerate? sourceData, SourceProductionContext ctx)
    {
        if (sourceData is null)
        {
            return;
        }

        if (sourceData.Errors.Count > 0)
        {
            var diagHelper = new DiagnosticHelper(ctx.ReportDiagnostic);
            foreach (var error in sourceData.Errors)
            {
                diagHelper.ReportError(error);
            }

            return;
        }

        var genHelper = new UnionGenHelper(sourceData);
        var result = genHelper.GeneratePartialStruct();
        ctx.AddSource(sourceData.HintName, SourceText.From(result, Encoding.UTF8));
    }

    private static UnionToGenerate? GetUnionToGenerate(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetNode is not StructDeclarationSyntax structSyntax
            || ctx.TargetSymbol is not INamedTypeSymbol structSymbol
            || ctx.Attributes.Length == 0)
        {
            return null;
        }

        var typeArguments = ctx.Attributes[0].AttributeClass?.TypeArguments ?? ImmutableArray<ITypeSymbol>.Empty;
        if (typeArguments.Length < MinTypeParameters)
        {
            return null;
        }

        // If any type argument failed to bind, the compiler already reports CS0246 on the user's
        // attribute usage - emitting our own diagnostic would just be noise, so we stay silent.
        foreach (var typeArgument in typeArguments)
        {
            if (typeArgument.TypeKind == TypeKind.Error)
            {
                return null;
            }
        }

        var annotatedType = structSyntax.Identifier.Text;
        var containingNamespace = structSymbol.ContainingNamespace;
        if (containingNamespace is null || containingNamespace.IsGlobalNamespace)
        {
            return UnionToGenerate.ForError(annotatedType,
                                            new DiagnosticHelper.Error(DiagnosticHelper.ErrorIds.GlobalNamespace,
                                                                       "Union types must be declared within a namespace"));
        }

        var typeNames = GetTypeParameters(typeArguments);
        var typeErrors = ValidateTypeParameters(typeNames);
        if (typeErrors.Count > 0)
        {
            return UnionToGenerate.ForError(annotatedType, typeErrors);
        }

        var structNamespace = containingNamespace.ToDisplayString();
        var structVisibility = GetVisibilityModifier(structSyntax);
        var (parentTypes, nestingErrors) = HandleNestedTypes(structSyntax);
        if (nestingErrors.Count > 0)
        {
            return UnionToGenerate.ForError(annotatedType, nestingErrors);
        }

        return new UnionToGenerate(annotatedType, structNamespace, structVisibility,
                                   new(typeNames),
                                   new(parentTypes),
                                   new([]));
    }

    private static List<DiagnosticHelper.Error> ValidateTypeParameters(List<TypeParameter> typeParameters)
    {
        var errors = new List<DiagnosticHelper.Error>();
        var seenFullNames = new HashSet<string>(StringComparer.Ordinal);
        var seenMemberNames = new HashSet<string>(StringComparer.Ordinal);

        foreach (var type in typeParameters)
        {
            if (!seenFullNames.Add(type.FullName))
            {
                errors.Add(new DiagnosticHelper.Error(DiagnosticHelper.ErrorIds.DuplicateType,
                                                      $"The type '{type.FullName}' is used more than once; each union case must be a distinct type"));

                continue;
            }

            if (!seenMemberNames.Add(type.WellKnownName))
            {
                errors.Add(new DiagnosticHelper.Error(DiagnosticHelper.ErrorIds.DuplicateMemberName,
                                                      $"Multiple union cases map to the generated name '{type.WellKnownName}'; rename or wrap one of the conflicting types"));
            }
        }

        return errors;
    }

    private static (List<ParentType> ParentTypes, List<DiagnosticHelper.Error> Errors) HandleNestedTypes(
        SyntaxNode structSyntax)
    {
        if (structSyntax.Parent is BaseNamespaceDeclarationSyntax)
        {
            return ([], []);
        }

        var parentTypes = new List<ParentType>();
        var currentType = structSyntax.Parent;
        do
        {
            if (currentType is TypeDeclarationSyntax typeDeclaration)
            {
                var partialFound = false;
                foreach (var modifier in typeDeclaration.Modifiers)
                {
                    if (modifier.IsKind(SyntaxKind.PartialKeyword))
                    {
                        partialFound = true;
                    }
                }

                if (!partialFound)
                {
                    return ([], [
                        new DiagnosticHelper.Error(DiagnosticHelper.ErrorIds.NestingNotPartial, "Union type can only be nested within a partial type")
                    ]);
                }

                var name = typeDeclaration.Identifier.Text;
                var visibility = GetVisibilityModifier(typeDeclaration);
                switch (typeDeclaration)
                {
                    case ClassDeclarationSyntax:
                        parentTypes.Add(new ParentType(name, ParentType.Class, visibility));

                        break;
                    case InterfaceDeclarationSyntax:
                        parentTypes.Add(new ParentType(name, ParentType.Interface, visibility));

                        break;
                    case StructDeclarationSyntax:
                        parentTypes.Add(new ParentType(name, ParentType.Struct, visibility));

                        break;
                    default:
                        return (
                            [],
                            [
                                new DiagnosticHelper.Error(DiagnosticHelper.ErrorIds.NestingUnknownParent,
                                                           $"Union type cannot be declared nested in {typeDeclaration.Kind()}")
                            ]);
                }
            }

            currentType = currentType?.Parent;
        } while (currentType is not null && currentType is not BaseNamespaceDeclarationSyntax);

        return (parentTypes, []);
    }

    private static List<TypeParameter> GetTypeParameters(ImmutableArray<ITypeSymbol> typeArguments)
    {
        var typeNames = new List<TypeParameter>(typeArguments.Length);
        foreach (var typeSymbol in typeArguments)
        {
            var name = typeSymbol.Name;
            var fullName = typeSymbol.ToString();
            var globalName = typeSymbol.ToDisplayString(globalQualifiedFormat);
            var isReferenceType = typeSymbol.IsReferenceType;
            var isInterface = typeSymbol.TypeKind == TypeKind.Interface;
            var isBuiltInType = typeSymbol.SpecialType != SpecialType.None;
            if (isBuiltInType)
            {
                name = fullName;
            }

            if (typeSymbol is INamedTypeSymbol { IsGenericType: true } namedTypeSymbol)
            {
                var typeArgs = namedTypeSymbol.TypeArguments;
                switch (typeArgs.Length)
                {
                    case 1:
                    {
                        var typeParamName = GetTypeParamName(typeArgs, 0);
                        if (typeParamName is not null)
                        {
                            name = $"{name}Of{typeParamName}";
                        }

                        break;
                    }
                    case 2:
                    {
                        var typeParam1Name = GetTypeParamName(typeArgs, 0);
                        var typeParam2Name = GetTypeParamName(typeArgs, 1);
                        if (typeParam1Name is not null && typeParam2Name is not null)
                        {
                            name = $"{name}Of{typeParam1Name}And{typeParam2Name}";
                        }

                        break;
                    }
                    default:
                    {
                        name = $"Generic{name}";

                        break;
                    }
                }
            }

            name = SanitizeName(name, fullName);

            typeNames.Add(new TypeParameter(name, fullName, globalName, isReferenceType, isInterface));
        }

        return typeNames;

        static string? GetTypeParamName(ImmutableArray<ITypeSymbol> typeParameters, int index)
        {
            var typeParameterSymbol = typeParameters[index];
            if (typeParameterSymbol is not INamedTypeSymbol namedSymbol)
            {
                return null;
            }

            var name = namedSymbol.Name;
            var titleCaseName = name.EnsureTitleCase();
            var adjustedName = WellKnownTypes.AdjustIfWellKnown(titleCaseName);

            return adjustedName;
        }
    }

    private static string SanitizeName(string? rawName, string fullName)
    {
        var name = string.IsNullOrWhiteSpace(rawName)
            ? fullName
            : rawName!;

        name = name.Replace("[]", "Array");
        var matches = nameFromFullNameRegex.Matches(name);
        if (matches.Count > 0)
        {
            name = matches[0].Groups[1].Value;
        }

        return name;
    }

    private static string GetVisibilityModifier(MemberDeclarationSyntax baseTypeSyntax)
    {
        for (var i = 0; i < baseTypeSyntax.Modifiers.Count; i++)
        {
            var modifier = baseTypeSyntax.Modifiers[i];
            switch (modifier.Kind())
            {
                case SyntaxKind.PublicKeyword:
                {
                    return "public";
                }
                case SyntaxKind.PrivateKeyword:
                {
                    return "private";
                }
                case SyntaxKind.InternalKeyword:
                {
                    return "internal";
                }
                case SyntaxKind.ProtectedKeyword:
                {
                    return "protected";
                }
                default:
                    continue;
            }
        }

        // No explicit modifier: omit it from the generated partial as well, so the C# compiler
        // applies the same implicit default the user's declaration gets (internal at namespace
        // scope, private when nested). Emitting an explicit modifier here would be wrong for one
        // of those cases (e.g. a top-level struct can never be private).
        return string.Empty;
    }
}
