using System.Text;

namespace UnionGen;

internal readonly struct UnionGenHelper(UnionToGenerate union)
{
    private const string TypeLookupFunc = "GetTypeName";
    private const string IndexParameterName = "index";
    private const string ActualTypeIndexParameterName = "actualTypeIndex";
    private const string StateByteFieldName = "_state";
    private const string IndexPropertyName = $"{StateByteFieldName}.Index";
    private const string ActualTypeIndexPropertyName = $"{StateByteFieldName}.ActualTypeIndex";
    private const string ValueParameterName = "value";
    private const string ValueFieldNamePrefix = $"_{ValueParameterName}";
    private const string RefValueFieldName = $"_{ValueParameterName}Ref";
    private const string GenNamespace = "global::UnionGen";
    private const string AggressiveInlining =
        "[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]";
    private const string StateByteTypeName = $"{GenNamespace}.InternalUtil.StateByte";
    private const string RefTypeIndex = $"{StateByteTypeName}.RefTypeIndex";
    private const string ThrowHelperType = $"{GenNamespace}.InternalUtil.ExceptionHelper";
    private const string ConstantsType = $"{GenNamespace}.InternalUtil.UnionGenInternalConst";

    public string GeneratePartialStruct()
    {
        var (prefixNesting, postfixNesting) = GetParentTypeNesting();
        var (typeFields, typeProperties) = GenerateFieldsAndProperties();

        var unionBuilder = new StringBuilder();
        unionBuilder.AppendLine(UnionSourceGen.AutoGeneratedComment);
        unionBuilder.AppendLine("#nullable enable");
        unionBuilder.AppendLine($"namespace {union.Namespace}");
        unionBuilder.AppendLine("{");
        unionBuilder.AppendLine(prefixNesting);
        unionBuilder.AppendLine($"    {union.Visibility} readonly partial struct {union.Name} : global::System.IEquatable<{union.Name}>");
        unionBuilder.AppendLine("    {");
        unionBuilder.AppendLine(typeFields);
        unionBuilder.AppendLine(GenerateConstructors());
        unionBuilder.AppendLine(typeProperties);
        unionBuilder.AppendLine(GenerateAccessors());
        unionBuilder.AppendLine(GenerateImplicitOperators());
        unionBuilder.AppendLine(GenerateMatch());
        unionBuilder.AppendLine(GenerateMatchAsync());
        unionBuilder.AppendLine(GenerateSwitch());
        unionBuilder.AppendLine(GenerateSwitchAsync());
        unionBuilder.AppendLine(GenerateToString());
        unionBuilder.AppendLine(GenerateEqualityMembers());
        unionBuilder.AppendLine(GenerateGetTypeName());
        unionBuilder.AppendLine("    }");
        unionBuilder.AppendLine(postfixNesting);
        unionBuilder.AppendLine("}");

        return unionBuilder.ToString();
    }

    private (string? PrefixNesting, string? PostfixNesting) GetParentTypeNesting()
    {
        if (union.ParentTypes.Count == 0)
        {
            return (string.Empty, string.Empty);
        }

        var prefix = new StringBuilder();
        foreach (var parentType in union.ParentTypes.Reverse())
        {
            prefix.AppendLine($"{parentType.Visibility} partial {parentType.Type} {parentType.Name} {{");
        }

        var postfix = new StringBuilder();
        for (var i = 0; i < union.ParentTypes.Count; i++)
        {
            postfix.AppendLine("}");
        }

        return (prefix.ToString(), postfix.ToString());
    }

    private string GenerateEqualityMembers()
    {
        var members = new StringBuilder();

        members.AppendLine(GenerateTypedEquals());
        members.AppendLine(GenerateObjectEquals());
        members.Append(GenerateGetHashCode());

        return members.ToString();
    }

    private string GenerateObjectEquals()
    {
        var equalsMethod = new IndentedStringBuilder(2);
        equalsMethod.AppendLine(AggressiveInlining);
        equalsMethod.AppendLine("public override bool Equals(object? obj)");
        equalsMethod.AppendLine("{");
        equalsMethod.AppendLine("if (ReferenceEquals(null, obj))", 1);
        equalsMethod.AppendLine("{", 1);
        equalsMethod.AppendLine("return false;", 2);
        equalsMethod.AppendLine("}", 1);
        equalsMethod.AppendLine($"return obj is {union.Name} other && Equals(other);", 1);
        equalsMethod.AppendLine("}");

        return equalsMethod.ToString();
    }

    private string GenerateTypedEquals()
    {
        // Switch on ActualTypeIndex (not Index): Index is the shared RefTypeIndex sentinel for every
        // reference case, so using it would make two distinct reference cases holding equal values
        // compare equal even though Switch/Match/Is* treat them as different cases.
        var method = new IndentedStringBuilder(2);
        method.AppendLine(AggressiveInlining);
        method.AppendLine($"public bool Equals({union.Name} other) => ");
        method.AppendLine($"{ActualTypeIndexPropertyName} == other.{ActualTypeIndexPropertyName}", 1);
        method.AppendLine($"&& {ActualTypeIndexPropertyName} switch ", 2);
        method.AppendLine("{", 2);

        for (var i = 0; i < union.TypeParameters.Count; i++)
        {
            var type = union.TypeParameters[i];
            method.AppendLine(type.IsReferenceType
                                  ? $"{i} => ReferenceEquals({RefValueFieldName}, other.{RefValueFieldName}) || ({RefValueFieldName}?.Equals(other.{RefValueFieldName}) ?? false),"
                                  : $"{i} => {ValueFieldNamePrefix}{i}.Equals(other.{ValueFieldNamePrefix}{i}),",
                              3);
        }

        method.AppendLine("_ => false", 3);
        method.AppendLine("};", 2);

        return method.ToString();
    }

    private string GenerateSwitch() => GenerateSwitch(false);

    private string GenerateSwitchAsync() => GenerateSwitch(true);

    private string GenerateSwitch(bool asAsync)
    {
        var parameters = new StringBuilder();
        var cases = new IndentedStringBuilder(4);

        var delegateType = asAsync ? "global::System.Func" : "global::System.Action";
        var secondParameter = asAsync ? ", global::System.Threading.Tasks.ValueTask" : string.Empty;
        var awaitPrefix = asAsync ? "await " : string.Empty;
        for (var i = 0; i < union.TypeParameters.Count; i++)
        {
            var type = union.TypeParameters[i];
            var actionName = $"for{type.TitleCaseName}";
            parameters.Append($"{delegateType}<{type.GlobalName}{secondParameter}> {actionName}");
            if (i < union.TypeParameters.Count - 1)
            {
                parameters.Append(", ");
            }

            cases.AppendLine(type.IsReferenceType
                                 ? $"case {i}: {awaitPrefix}{actionName}(({type.GlobalName}){RefValueFieldName}!); break;"
                                 : $"case {i}: {awaitPrefix}{actionName}({ValueFieldNamePrefix}{i}); break;");
        }

        cases.AppendLine($"default: throw {ThrowHelperType}.ThrowUnknownTypeIndex({ActualTypeIndexPropertyName});");

        var methodSignature = asAsync ? "async global::System.Threading.Tasks.ValueTask SwitchAsync" : "void Switch";
        var switchMethod = new IndentedStringBuilder(2, $"public {methodSignature}(");
        switchMethod.Append(parameters.ToString());
        switchMethod.Append(")");
        switchMethod.AppendLine(string.Empty);
        switchMethod.AppendLine("{");
        switchMethod.AppendLine($"switch ({ActualTypeIndexPropertyName})", 1);
        switchMethod.AppendLine("{", 1);
        switchMethod.Append(cases.ToString());
        switchMethod.AppendLine("}", 1);
        switchMethod.AppendLine("}");

        return switchMethod.ToString();
    }

    private string GenerateMatch() => GenerateMatch(false);
    private string GenerateMatchAsync() => GenerateMatch(true);

    private string GenerateMatch(bool asAsync)
    {
        var parameters = new StringBuilder();
        var cases = new IndentedStringBuilder(4);
        var secondParameter = asAsync ? "global::System.Threading.Tasks.ValueTask<TResult>" : "TResult";
        var awaitPrefix = asAsync ? "await " : string.Empty;
        for (var i = 0; i < union.TypeParameters.Count; i++)
        {
            var type = union.TypeParameters[i];
            var funcName = $"with{type.TitleCaseName}";
            parameters.Append($"global::System.Func<{type.GlobalName}, {secondParameter}> {funcName}");
            if (i < union.TypeParameters.Count - 1)
            {
                parameters.Append(", ");
            }

            cases.AppendLine(type.IsReferenceType
                                 ? $"{i} => {awaitPrefix}{funcName}(({type.GlobalName}){RefValueFieldName}!),"
                                 : $"{i} => {awaitPrefix}{funcName}({ValueFieldNamePrefix}{i}),");
        }

        cases.AppendLine($"_ => throw {ThrowHelperType}.ThrowUnknownTypeIndex({ActualTypeIndexPropertyName})");

        var methodSignature = asAsync ? "async global::System.Threading.Tasks.ValueTask<TResult> MatchAsync<TResult>" : "TResult Match<TResult>";
        var matchMethod = new IndentedStringBuilder(2, $"public {methodSignature}({parameters})");
        matchMethod.Append(" => ");
        matchMethod.AppendLine(string.Empty);
        matchMethod.AppendLine($"{ActualTypeIndexPropertyName} switch", 1);
        matchMethod.AppendLine("{", 1);
        matchMethod.Append(cases);
        matchMethod.AppendLine("};", 1);

        return matchMethod.ToString();
    }

    private string GenerateToString()
    {
        var cases = new IndentedStringBuilder(4);

        for (var i = 0; i < union.TypeParameters.Count; i++)
        {
            var type = union.TypeParameters[i];
            cases.AppendLine(type.IsReferenceType
                                 ? $"{i} => {RefValueFieldName}?.ToString() ?? {ConstantsType}.NullString,"
                                 : $"{i} => {ValueFieldNamePrefix}{i}{type.CallOperator}ToString()!,");
        }

        cases.AppendLine($"_ => throw {ThrowHelperType}.ThrowUnknownTypeIndex({ActualTypeIndexPropertyName})");

        var toStringMethod = new IndentedStringBuilder(2, "public override string ToString()");
        toStringMethod.Append(" => ");
        toStringMethod.AppendLine(string.Empty);
        toStringMethod.AppendLine($"{ActualTypeIndexPropertyName} switch", 1);
        toStringMethod.AppendLine("{", 1);
        toStringMethod.Append(cases);
        toStringMethod.AppendLine("};", 1);

        return toStringMethod.ToString();
    }

    private string GenerateGetHashCode()
    {
        var cases = new IndentedStringBuilder(5);
        for (var i = 0; i < union.TypeParameters.Count; i++)
        {
            var type = union.TypeParameters[i];
            cases.AppendLine(type.IsReferenceType
                                 ? $"{i} => {RefValueFieldName}?.GetHashCode() ?? 0,"
                                 : $"{i} => {ValueFieldNamePrefix}{i}{type.CallOperator}GetHashCode(),");
        }

        cases.AppendLine("_ => 0");

        var hashCodeMethod = new IndentedStringBuilder(2);
        hashCodeMethod.AppendLine(AggressiveInlining);
        hashCodeMethod.AppendLine("public override int GetHashCode()");
        hashCodeMethod.AppendLine("{");
        hashCodeMethod.AppendLine("unchecked", 1);
        hashCodeMethod.AppendLine("{", 1);
        hashCodeMethod.AppendLine($"var hash = {ActualTypeIndexPropertyName} switch", 2);
        hashCodeMethod.AppendLine("{", 2);
        hashCodeMethod.Append(cases);
        hashCodeMethod.AppendLine("};", 2);
        hashCodeMethod.AppendLine($"return (hash * 397) ^ {ActualTypeIndexPropertyName};", 2);
        hashCodeMethod.AppendLine("}", 1);
        hashCodeMethod.AppendLine("}");

        return hashCodeMethod.ToString();
    }

    private string GenerateImplicitOperators()
    {
        var operators = new IndentedStringBuilder(2);

        foreach (var type in union.TypeParameters.Where(tp => !tp.IsInterface))
        {
            operators.AppendLine(AggressiveInlining);
            operators.AppendLine($"public static implicit operator {union.Name}({type.GlobalName} {ValueParameterName}) => new {union.Name}({ValueParameterName});");
        }

        operators.AppendLine(AggressiveInlining);
        operators.AppendLine($"public static bool operator ==({union.Name} left, {union.Name} right) => left.Equals(right);");
        operators.AppendLine(AggressiveInlining);
        operators.AppendLine($"public static bool operator !=({union.Name} left, {union.Name} right) => !left.Equals(right);");

        return operators.ToString();
    }

    private string GenerateConstructors()
    {
        var constructors = new IndentedStringBuilder(2);
        constructors.AppendLine(AggressiveInlining);
        constructors.AppendLine(GeneratePrivateConstructor());

        for (var i = 0; i < union.TypeParameters.Count; i++)
        {
            var type = union.TypeParameters[i];

            string index;
            string valueField;
            if (type.IsReferenceType)
            {
                index = RefTypeIndex;
                valueField = RefValueFieldName;
            }
            else
            {
                index = i.ToString();
                valueField = $"{ValueFieldNamePrefix}{i}";
            }

            var constructor
                = new IndentedStringBuilder(0, $"public {union.Name}({type.GlobalName} {ValueParameterName})");
            constructor.Append($": this({index}, {i}){IndentedStringBuilder.NewLine}");
            constructor.AppendLine("{", 2);
            constructor.AppendLine($"{valueField} = {ValueParameterName};", 3);
            constructor.AppendLine("}", 2);
            constructors.AppendLine(AggressiveInlining);
            constructors.AppendLine(constructor.ToString());
        }

        constructors.AppendLine($"[global::System.Obsolete({ConstantsType}.DefaultConstructorWarning, true)]");
        constructors.AppendLine($"public {union.Name}(): this(0, 0) {{}}");

        return constructors.ToString();
    }

    private string GeneratePrivateConstructor()
    {
        var constructor
            = new IndentedStringBuilder(0,
                                        $"private {union.Name}(int {IndexParameterName}, int {ActualTypeIndexParameterName}){IndentedStringBuilder.NewLine}");
        constructor.AppendLine("{", 2);
        constructor.AppendLine($"{StateByteFieldName} = new {StateByteTypeName}({IndexParameterName}, {ActualTypeIndexParameterName});",
                               3);
        constructor.AppendLine("}", 2);

        return constructor.ToString();
    }

    private string GenerateGetTypeName()
    {
        var func = new IndentedStringBuilder(2);
        func.AppendLine(AggressiveInlining);
        func.AppendLine($"public string {TypeLookupFunc}(int index) =>");
        func.AppendLine($"index switch ", 1);
        func.AppendLine("{", 1);
        for (var i = 0; i < union.TypeParameters.Count; i++)
        {
            var type = union.TypeParameters[i];
            func.AppendLine($"{i} => \"{type.FullName}\",", 2);
        }

        func.AppendLine($"_ => throw {ThrowHelperType}.ThrowUnknownTypeIndex(index)",
                        2);
        func.AppendLine("};", 1);

        return func.ToString();
    }

    private string GenerateAccessors()
    {
        var accessors = new IndentedStringBuilder(2);
        for (var i = 0; i < union.TypeParameters.Count; i++)
        {
            var type = union.TypeParameters[i];
            accessors.AppendLine(AggressiveInlining);
            accessors.AppendLine($"public {type.GlobalName} As{type.WellKnownName}() =>");
            accessors.AppendLine($"Is{type.WellKnownName}", 1);
            accessors.AppendLine(type.IsReferenceType
                                     ? $"? ({type.GlobalName}) {RefValueFieldName}!"
                                     : $"? {ValueFieldNamePrefix}{i}",
                                 2);
            accessors.AppendLine($": throw {ThrowHelperType}.ThrowNotOfType({TypeLookupFunc}({i}), {TypeLookupFunc}({ActualTypeIndexPropertyName}));",
                                 2);

            if (i < union.TypeParameters.Count - 1)
            {
                accessors.AppendLine(string.Empty);
            }
        }

        return accessors.ToString();
    }

    private (string TypeFields, string TypeProperties) GenerateFieldsAndProperties()
    {
        var typeProperties = new IndentedStringBuilder(2);
        var typeFields = new IndentedStringBuilder(2);

        if (union.AnyReferenceType())
        {
            typeFields.AppendLine($"private readonly object? {RefValueFieldName};");
        }

        for (var i = 0; i < union.TypeParameters.Count; i++)
        {
            var type = union.TypeParameters[i];

            if (!type.IsReferenceType)
            {
                typeFields.AppendLine($"private readonly {type.GlobalName} {ValueFieldNamePrefix}{i};");
            }

            typeProperties.AppendLine($"public bool Is{type.WellKnownName}");
            typeProperties.AppendLine("{");
            typeProperties.AppendLine($"{AggressiveInlining} get => {ActualTypeIndexPropertyName} == {i};", 1);
            typeProperties.AppendLine("}");
        }

        typeFields.AppendLine($"private readonly {StateByteTypeName} {StateByteFieldName};");

        return (typeFields.ToString(), typeProperties.ToString());
    }
}
